### ISSUE TITLE
No Game Instructions

### ISSUE THREAD

**Issue by KeithNdhlovu** [emelent/foolish-love#1]
How do we play?

**Comment by emelent** [comment]
Hahaha, ah Keith my man, it's been a while hombre. Unfortunately it's not a game yet. This wasn't meant to be "public" public, I just needed to test how the web deployment works, and if I can get some auto deployment with github actions to netlify. At the moment I'm using this to get back into love2d and learn some things...

**Comment by KeithNdhlovu** [comment]
Aweh, well that makes sense, yeah GH Actions were a welcomed addition to GitHub to make use of the ecosystem to also do CI/CD i have helped some folks do deployments and releases via this method, its quite simplistic in its approach compared to the likes of Azure DevOps.

Sound like you having fun, Happy Coding Hombrero 😄
